steps:
- task: CopyFiles@2
  displayName: Copy ARM template
  inputs:
    SourceFolder: 'azure/arm'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/arm'
    CleanTargetFolder: true
    OverWrite: true
    
- task: CopyFiles@2
  displayName: Copy CLI powershell
  inputs:
    SourceFolder: 'azure/cli'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/arm'
    OverWrite: true

- task: CopyFiles@2
  displayName: Copy ARM parameters
  inputs:
    SourceFolder: 'azure/parameters'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/arm_parameters'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: artifacts

- task: Npm@1
  displayName: NPM install
  inputs:
    workingDir: func
    verbose: false

- task: CopyFiles@2
  displayName: Copy Azure Function Files
  inputs:
    SourceFolder: func
    TargetFolder: '$(Build.ArtifactStagingDirectory)/functions'

- task: ArchiveFiles@2
  displayName: Archive $(Build.ArtifactStagingDirectory)/functions
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/functions'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/functions.zip'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact Functions
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/functions.zip'
    ArtifactName: functions
