queue:
  name: Hosted VS2017
  condition: succeeded()
steps:
- task: CopyFiles@2
  displayName: Copy ARM template
  inputs:
    SourceFolder: 'azure/arm'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/arm'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/arm'
    ArtifactName: arm
