steps:
- task: CopyFiles@2
  displayName: Copy ARM template
  inputs:
    SourceFolder: 'azure/arm'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/arm'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish ARM Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/arm'
    ArtifactName: arm
    
- task: CopyFiles@2
  displayName: Copy ARM parameters
  inputs:
    SourceFolder: 'azure/parameters'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/arm_parameters'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish ARM Parameter Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/arm_parameters'
    ArtifactName: arm_parameters
