# Global settings applied to the whole site.
[build]
  base    = "jam"
  publish = "public"
  command = "gatsby build"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "gatsby build"

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.feature]
  command = "gatsby build"

[context."features/branch"]
  command = "gatsby build"

